topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/config/routes.rb
Rails.application.routes.draw do


  resources :livros
  resources :users

  resources :sessions do
    collection do
      match 'search' => 'sessions#search', via: [:get, :post], as: :search
    end
  end

  root 'sessions#index'

  get    'homeUser'  => 'users#index'
  get    'search'  => 'sessions#show'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'


  get 'sessions/search'

end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/models/livro.rb
class Livro < ActiveRecord::Base
  has_attached_file :image, styles: { medium: "6000x400", thumb: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates_presence_of :titulo, :autor, :editora
  validates_uniqueness_of :titulo
  default_value_for :visita, 0

end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/models/user.rb
class User < ActiveRecord::Base

 # ##before_save { self.email = email.downcase }
  #validates :name,  presence: true, length: { maximum: 50 }
 # VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
 # validates :email, presence: true, length: { maximum: 255 },
  #          format: { with: VALID_EMAIL_REGEX },
  #          uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  validates_presence_of :email, :username, :password
  validates_confirmation_of :password
  validates_uniqueness_of :email, :username

  EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  private
  validate do
    errors.add(:email, :invalid) unless email.match(EMAIL_REGEXP)
  end
  # Returns the hash digest of the given string.
 # def User.digest(string)
  #  cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
   #     BCrypt::Engine.cost
    #BCrypt::Password.create(string, cost: cost)
    #end


end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #include SessionsHelper

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end
end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :set_livro, only: [:show, :edit, :update, :destroy, :search, :curtir]
  before_action :require_user, only: [:index, :show]

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  # GET /livros/1
  # GET /livros/1.json
  def show


  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
  end


  def search

  end

  def curtir
    @livro = Livro.find(params[:id])
    @livro.id = @livro.id + 1

  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { redirect_to @livro, notice: 'Livro was successfully created.' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Livro was successfully updated.' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro.destroy
    respond_to do |format|
      format.html { redirect_to homeUser_path, notice: 'Livro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :editora, :ano, :sinopse, :image, :visita)
    end
end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/homeUser'
    else
      flash.now[:error] = "Could not create client"
      redirect_to 'login'
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

  def index
  end


  def show

#      busca_titulo = params[:search_titulo].to_s
 #     @livros = Livro.where("titulo LIKE ?","%#{busca_titulo}%")

    @q = Livro.ransack(params[:q].try(:merge, m: 'and' ))
    @livros = @q.result



  end


  def search
    show
    render :show
  end

  end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, only: [:index, :show, :edit]


  def index

   # @users = User.all
    ids= Livro.last.id
    @livros1 = Livro.where(id: ((ids-4)..ids))


  end
  def show
    @user = User.find(params[:id])

  end

  def new
    @user = User.new
  end

  def edit
    @user = current_user
  end

  def create
    #@user = User.new(user_params)

    #respond_to do |format|
     # if @user.save
     #   format.html { redirect_to @user, notice: 'User was successfully created.' }
     #   format.json { render :show, status: :created, location: @user }
     # else
     #   format.html { render :new }
     #   format.json { render json: @user.errors, status: :unprocessable_entity }
     # end
    #end

    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/homeUser'
    else
      redirect_to '/signup'
    end

  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :password, :username, :email, :sexo)
    end
end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/helpers/application_helper.rb
module ApplicationHelper
  def flash_message
    messages = ""
    [:notice, :info, :warning, :error].each {|type|
      if flash[type]
        messages += "<p class=\"#{type}\">#{flash[type]}</p>"
      end
    }

    messages
  end
end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/helpers/livros_helper.rb
module LivrosHelper
end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


  def logged_in
    !current_user.nil?
  end


  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/helpers/users_helper.rb
module UsersHelper


end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WSBooks</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/views/livros/_form.html.erb
<%= form_for(@livro) do |f| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% @livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="teste">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :editora %><br>
    <%= f.text_field :editora %>
  </div>
  <div class="field">
    <%= f.label :ano %><br>
    <%= f.number_field :ano %>
  </div>
  <div class="field">
    <%= f.label :sinopse %><br>
    <%= f.text_area :sinopse %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/views/livros/edit.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Cadastro Usuario| WS book's</title>

  <%= stylesheet_link_tag "bootstrap.min", "font-awesome.min", "animate.min", "lightbox", "main", "responsive", "sweetalert", "star-rating"%>
  <%= javascript_include_tag "html5shiv", "respond", "jquery", "bootstrap.min", "lightbox.min", "wow.min", "main", "sweetalert.min", "jsFunctions", "star-rating" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js" %>

  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>


  <!--[if lt IE 9]>
</head><!--/head-->
  <style type="text/css">

    #labelImg{
      margin-top:2%;
    }
  </style>
<body>
<header id="header">


  <div class="navbar navbar-inverse" role="banner">
    <div class="container">



      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand">
          <h1><%= link_to image_tag("logo.png"), homeUser_path %></h1>

        </a>



      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown"> <li><%= link_to "Home", homeUser_path %></li></li>
          <li class="dropdown"><a>Livros <i class="fa fa-angle-down"></i></a></li>
          <ul role="menu" class="sub-menu">
            <li><%= link_to "Buscar", sessions_search_path %></li>
            <li><%= link_to "Inserir", new_livro_path %></li>
          </ul>
          </li>

          <li class="active"><a href=""><%=current_user.username %><i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>

            </ul>
          </li>

        </ul>
      </div>
      <!--
      LUPA DE PESQUISA
///////////////////////////////////////////////////////////////////////////////////////////////
      <div class="search">
           <form role="form">
               <i class="fa fa-search"></i>
               <div class="field-toggle">
                   <input type="text" class="search-form" autocomplete="on" placeholder="Search">
               </div>
           </form>
       </div>
       ///////////////////////////////////////////////////////////////////////////////////////////////
-->
    </div>
  </div>

  </div>
  </div>
</header>
<!--/#header-->
->


<section id="page-breadcrumb">
  <div class="vertical-center sun">
    <div class="container">
      <div class="row">
        <div class="action">
          <div class="col-sm-12">
            <h1 class="title">Cadastro de Livros</h1>
            <!--<p>Why our Clients love to work with us.</p>-->
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!--/#page-breadcrumb-->


<!-- BASIC FORM ELELEMNTS -->
<div class="row mt">
  <div class="col-lg-12">
    <div class="form-panel">
      <br>
      <br>

      <%= form_for(@livro) do |f| %>


          <div class="form-group">
            <div class="formsCadastro">
              <%= f.label :titulo %><br>
              <%= f.text_field :titulo %>
            </div>
          </div>



          <div class="form-group">
            <div class="formsCadastro">
              <%= f.label :autor %><br>
              <%= f.text_field :autor %>
            </div>
          </div>

          <div class="form-group">
            <div class="formsCadastro">
              <%= f.label :editora %><br>
              <%= f.text_field :editora %>
            </div>


          </div>


          <div class="form-group">
            <div class="formsCadastro">
              <%= f.label :ano %><br>
              <%= f.number_field :ano %>
            </div>


          </div>




          <div class="form-group">
            <div class="formsCadastro">
              <%= f.label :sinopse %><br>
              <%= f.text_area :sinopse %>
            </div>



          </div>



          <div class="form-group">
            <div class="formsCadastro">
              <%= f.label :image %><br>
              <%= f.file_field :image %>
            </div>

          </div>

          <%= f.submit "Update", class: "btn btn-sm btn-info botaoEnviarCadastroLivro actions" %>




          <!--<a href="CadastroUsuario.html" class="btn btn-sm btn-info" type="submit" id = "botaoEnviarCadastro">Enviar</a>-->

      <% end %>

    </div>
  </div><!-- col-lg-12-->
</div><!-- /row -->

<!--/#team-->

<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center bottom-separator">
        <%= image_tag "images/home/under.png", class:"img-responsive inline"%>
      </div>


      <table>
        <thead>
        <tr><h2 class="page-header">Frases</h2></tr>
        </thead>
        <tbody>
        <tr>
          <td><blockquote>
            <p>Quem lê muito e anda muito, vai longe e sabe muito.</p>
            <footer><cite title="Source Title">Cervantes, Miguel</cite></footer>
          </blockquote></td>
          <td><blockquote>
            <p>Dupla delícia</p>
            <p>O livro traz a vantagem de a gente poder estar só e ao mesmo tempo acompanhado.</p>
            <footer><cite title="Source Title">Quintana, Mario</cite></footer>
          </blockquote>
          </td>
        </tr>
        </tbody>
      </table>


      <div class="col-sm-12">
        <div class="copyright-text text-center">
          <p>&copy; Your Company 2014. All Rights Reserved.</p>
          <p>Designed by <a target="_blank" href="http://www.themeum.com">Themeum</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!--/#footer-->

</body>
</html>

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/views/livros/index.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Cadastro Usuario| WS book's</title>

  <%= stylesheet_link_tag "bootstrap.min", "font-awesome.min", "animate.min", "lightbox", "main", "responsive", "sweetalert", "star-rating"%>
  <%= javascript_include_tag "html5shiv", "respond", "jquery", "bootstrap.min", "lightbox.min", "wow.min", "main", "sweetalert.min", "jsFunctions", "star-rating" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js" %>

  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>


  <!--[if lt IE 9]>
</head><!--/head-->
  <style type="text/css">

    #labelImg{
      margin-top:2%;
    }
  </style>
<body>
<header id="header">


  <div class="navbar navbar-inverse" role="banner">
    <div class="container">



      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand">
          <h1><%= link_to image_tag("logo.png"), homeUser_path %></h1>

        </a>



      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown"> <li><%= link_to "Home", homeUser_path %></li></li>
          <li class="dropdown"><a>Livros <i class="fa fa-angle-down"></i></a></li>
          <ul role="menu" class="sub-menu">
            <li><%= link_to "Buscar", sessions_search_path %></li>
            <li><%= link_to "Inserir", new_livro_path %></li>
          </ul>
          </li>

          <li class="active"><a href=""><%=current_user.username %><i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>

            </ul>
          </li>

        </ul>
      </div>
      <!--
      LUPA DE PESQUISA
///////////////////////////////////////////////////////////////////////////////////////////////
      <div class="search">
           <form role="form">
               <i class="fa fa-search"></i>
               <div class="field-toggle">
                   <input type="text" class="search-form" autocomplete="on" placeholder="Search">
               </div>
           </form>
       </div>
       ///////////////////////////////////////////////////////////////////////////////////////////////
-->
    </div>
  </div>

  </div>
  </div>
</header>
<!--/#header-->

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/views/livros/show.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Cadastro Livro| WS book's</title>

  <%= stylesheet_link_tag "bootstrap.min", "font-awesome.min", "animate.min", "lightbox", "main", "responsive", "sweetalert", "star-rating"%>
  <%= javascript_include_tag "html5shiv", "respond", "jquery", "bootstrap.min", "lightbox.min", "wow.min", "main", "sweetalert.min", "jsFunctions", "star-rating" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js" %>

  <%= stylesheet_link_tag "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>


  <!--[if lt IE 9]>
</head-->
  <style type="text/css">

    #labelImg{
      margin-top:2%;
    }
  </style>
<body>
<header id="header">


  <div class="navbar navbar-inverse" role="banner">
    <div class="container">



      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand">
          <h1><%= link_to image_tag("logo.png"), homeUser_path %></h1>

        </a>



      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown"> <li><%= link_to "Home", homeUser_path %></li></li>
          <li class="active"><a href="">Livros <i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
              <li><%= link_to "Buscar", sessions_search_path %></li>
              <li><%= link_to "Inserir", new_livro_path %></li>
            </ul>
          </li>

          <li class="dropdown"><a href=""><%=current_user.username %><i class="fa fa-angle-down"></i></a>
            <ul role="menu" class="sub-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Log out", logout_path, method: "delete" %></li>

            </ul>
          </li>

        </ul>
      </div>
      <!--
      LUPA DE PESQUISA
///////////////////////////////////////////////////////////////////////////////////////////////
      <div class="search">
           <form role="form">
               <i class="fa fa-search"></i>
               <div class="field-toggle">
                   <input type="text" class="search-form" autocomplete="on" placeholder="Search">
               </div>
           </form>
       </div>
       ///////////////////////////////////////////////////////////////////////////////////////////////
-->
    </div>
  </div>

  </div>
  </div>
</header>

<!--/#header-->

<!-- section -->

<section id="portfolio-information" class="padding-top">
  <div class="container">
    <div class="row">
      <div class="livroImg">
        <%= image_tag(@livro.image.url(:medium))%>

      </div>
      <div class="infoLivro"><font face="Lato">
        <div class="project-name overflow">
          <h2 class="bold"><b><%= @livro.titulo %></b> </h2>
          <ul class="nav navbar-nav navbar-default">
            <li><a href="#"><i class="fa fa-tag"></i><%= @livro.autor %></a></li>
            <li><a href="#"><i class="fa fa-clock-o"></i><%= @livro.ano %></a></li>
            <li><a href="#"><i class="fa fa-tag"></i><%= @livro.editora %></a></li>

          </ul>
        </div>
        <div class="project-info overflow">
          <h3>Sipnose</h3>
          <p><%= @livro.sinopse %></p>
        </div>

        <br><br>
        <table>
    <tr>
         <td>    <%=button_to "Editar", edit_livro_path, method: :get, class: "btn btn-default" %></td> <br>

           <td>  <%=button_to "Excluir", @livro, method: :delete, class: "btn btn-default",  data: { confirm: 'Are you sure?' } %></td>


      <%= form_for @livro do |f| %>
          <td>  <%=button_to "<3", f, method: :curtir, class: "btn btn-default" %></td>
      <% end %>
      <%= link_to "New User", action_name: "curtir", :class => "button", :method => :get  %>

    </tr>

        </table>
      </div>
      </font></div>
  </div>
  </div>
</section>




<!-- end  section -->

<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 text-center bottom-separator">
        <%= image_tag "images/home/under.png", class:"img-responsive inline"%>
      </div>

      <table>
        <thead>
        <tr><h2 class="page-header">Frases</h2></tr>
        </thead>
        <tbody>
        <tr>
          <td><blockquote>
            <p>Quem lê muito e anda muito, vai longe e sabe muito.</p>
            <footer><cite title="Source Title">Cervantes, Miguel</cite></footer>
          </blockquote></td>
          <td><blockquote>
            <p>Dupla delícia</p>
            <p>O livro traz a vantagem de a gente poder estar só e ao mesmo tempo acompanhado.</p>
            <footer><cite title="Source Title">Quintana, Mario</cite></footer>
          </blockquote>
          </td>
        </tr>
        </tbody>
      </table>

      <div class="col-sm-12">
        <div class="copyright-text text-center">
          <p>&copy; Your Company 2014. All Rights Reserved.</p>
          <p>Designed by <a target="_blank" href="http://www.themeum.com">Themeum</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>
<!--/#footer-->

</body>
</html>

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :sexo %><br>
    <%= f.text_field :sexo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

topicos-especiais-programacao/WSBooks_rails/WSBooks - Rails/app/views/users/show.html.erb
<%= render 'edit' %>